name: Carbon_Chillax
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  form_field_validator: ^1.1.0
  http: ^1.5.0
  firebase_core: ^2.27.0
  smooth_page_indicator: ^1.2.1
  video_player: ^2.10.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/video/
